### PR TITLE
Fixing wrong repository package

### PR DESCRIPTION
**Pull request by eddynaka**
## Description
- fixing wrong repository package

### CODE REVIEW

**Review by marmegh — APPROVED** [review]
:shipit:

**Comment by michaelcfanning** [comment]
>     <Product Condition=" '$(Product)' == '' ">Microsoft SARIF Pattern Matcher</Product>

This looks wrong.

---
Refers to: src/Directory.Build.props:17 in 8cc395e. [](commit_id = 8cc395e1fbbd162ba82ad141bbd9cdb10b885fc9, deletion_comment = False)

**Comment by eddynaka** [comment]
>     <Product Condition=" '$(Product)' == '' ">Microsoft SARIF Pattern Matcher</Product>

Fixed!
thank you!


---
In reply to: [1007586821](https://github.com/microsoft/security-utilities/pull/4#issuecomment-1007586821) [](http://example.com/codeflow?ancestors=1007586821,1007586821)

---
Refers to: src/Directory.Build.props:17 in 8cc395e. [](commit_id = 8cc395e1fbbd162ba82ad141bbd9cdb10b885fc9, deletion_comment = False)

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Pull request merged**
